### PR TITLE
Stream to disk with io.Copy

### LINKED ISSUE #33: store-cli get fails with out of memory when downloading a large artifact
Seeing the following backtrace when trying to download a large zipped directory structure on an instance with limited memory

```
 19:57:18 $ store-cli get ./caches --type=cache --scope=pipeline || true ; echo skipping event cache ; store-cli get ./caches --type=cache --scope=job || true
19:57:49 fatal error: runtime: out of memory
19:57:49
19:57:49 runtime stack:
19:57:49 runtime.throw(0x7b7870, 0x16)
19:57:49 	/usr/local/go/src/runtime/panic.go:608 +0x72
19:57:49 runtime.sysMap(0xc044000000, 0x40000000, 0xa87278)
19:57:49 	/usr/local/go/src/runtime/mem_linux.go:156 +0xc7
19:57:49 runtime.(*mheap).sysAlloc(0xa6dfc0, 0x40000000, 0x0, 0x0)
19:57:49 	/usr/local/go/src/runtime/malloc.go:619 +0x1c7 
```

Looking at the code, it appears the interface attempts to download all the bytes into memory before then trying to write it to a file.  Seems it would be better to pass in a io.Writer so that the bytes can be written in a stream to the destination rather than trying to store it all in memory.

### LINKED ISSUE #1602: store-cli should stream data when download
Currently, store-cli is reads the whole response body and assign to a var: https://github.com/screwdriver-cd/store-cli/blob/master/sdstore/sdstore.go#L221

This might cause issue when the response body is too big and there is not enough memory. We can try to use `io.Copy` instead: https://medium.com/learning-the-go-programming-language/streaming-io-in-go-d93507931185

### PR DESCRIPTION
**Pull request by jacobtolar**
## Context

store-cli downloads large objects into memory, this is unnecessary and can cause users to require more memory for their jobs

## Objective

Use `io.Copy` to stream to disk.

## References

Fixes https://github.com/screwdriver-cd/store-cli/issues/33
Fixes https://github.com/screwdriver-cd/screwdriver/issues/1602

See https://golang.org/pkg/io/#Copy

## License

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

File: sdstore/sdstore.go [hunk 1]
```diff
@@ -217,41 +217,52 @@ func tokenHeader(token string) string {
...
 	}
 	defer res.Body.Close()
 
-	return handleResponse(res)
+	return handleResponse(res, nil)
 }
 
 // GET request from SD Store
-func (s *sdStore) get(url *url.URL, toExtract bool) ([]byte, error) {
+func (s *sdStore) get(url *url.URL, toExtract bool) error {
```
Comment (jacobtolar) [inline sdstore/sdstore.go]: If there is a concern that changing the function signature here is problematic I can do this differently, but it didn't look like anything was consuming this as a library.

**Comment by jacobtolar** [comment]
Oh, will fix the `go vet` and test issues.

Before/after showing the memory usage fix.

out

File: sdstore/sdstore_test.go [hunk 2]
```diff
@@ -357,43 +357,6 @@ func TestUploadZipRetry(t *testing.T) {
 	os.Remove("emitterdata_md5.json")
 }
 
-func TestDownload(t *testing.T) {
```
Comment (jacobtolar) [inline sdstore/sdstore_test.go:360]: I removed this test because Download no longer returns the entire contents as a `[]bytes` (that behavior wasn't used anywhere except in unit tests). 

Download is still tested elsewhere e.g. `TestDownloadWriteBack`.

File: sdstore/sdstore_test.go [hunk 3]
```diff
@@ -489,11 +452,7 @@ func TestDownloadWriteBack(t *testing.T) {
 	})
 
 	downloader.client = http
-	res, _ := downloader.Download(u, false)
-
-	if string(res) != want {
```
Comment (jacobtolar) [inline sdstore/sdstore_test.go:494]: Tested by reading file contents below already.

File: sdstore/sdstore_test.go [hunk 4]
```diff
@@ -533,11 +492,7 @@ func TestDownloadWriteBackSpecialFile(t *testing.T) {
...
```
Comment (jacobtolar) [inline sdstore/sdstore_test.go:538]: Tested by reading file contents below already.

**Review by minzcmu — APPROVED** [review]
LGTM 👍 Thank you for contributing!

**Review by jithine — APPROVED** [review]
